import { StyleSheet, Dimensions, Platform } from 'react-native';

const windowWidth = Dimensions.get('window').width;
const isIpad = Platform.OS === 'ios' && windowWidth > 768;

const colors = {
  primaryBackground: '#F0F0F0',
  tileBackground: '#333',
  cardText: '#8673F9',
  shadowColor: 'rgba(204, 204, 255, 0.8)',
  visualFlashcardBackground: '#F0F8FF',
  expandedFlashcardTitleTextShadow: 'rgba(0, 125, 125, 1)',
  buttonBackground: '#70B7ED',
  buttonText: '#fff',
  modalOverlay: 'rgba(0, 0, 0, 0.5)',
  modalContentBackground: '#fff',
  modalButtonBackground: '#FE89A9',
  modalButtonTextColor: '#fff',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.primaryBackground,
  },
  logo: {
    marginTop: 10,
    marginBottom: 10,
    width: isIpad ? '10%' : '30%',
    height: 60,
  },
  profileLogo: {
    marginTop: 10,
    marginBottom: 40,
    width: '100%',
    height: isIpad ? 200 : 100,
  },
  tilesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  tile: {
    margin: 5,
    padding: 20,
    borderRadius: 20,
    backgroundColor: colors.tileBackground,
    elevation: 5,
    alignItems: 'center',
    width: isIpad ? windowWidth / 5 - 10 : windowWidth / 3 - 10,
  },
  tileText: {
    fontSize: 10,
    letterSpacing: 1.5,
    fontWeight: '700',
    color: '#fff',
    marginTop: 10,
  },
  card: {
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 5,
    paddingRight: 25,
    borderRadius: 10,
    elevation: 5,
    flexDirection: 'row',
  },
  cardText: {
    fontSize: 15,
    fontWeight: '900',
    color: colors.cardText,
    textAlign: 'center',
  },
  NoCardText: {
    fontSize: 20,
    letterSpacing: 2,
    fontWeight: '600',
    color: '#000',
    textAlign: 'center',
    marginTop: '10%',
    textShadowColor: colors.shadowColor,
    textShadowOffset: { width: 5, height: 2 },
    textShadowRadius: 5,
  },
  image: {
    width: isIpad ? 400 : 300,
    height: isIpad ? 300 : 200,
    alignSelf: 'center',
    borderRadius: 20,
  },
  dateText: {
    fontWeight: '800',
    color: '#FFF',
    textAlign: 'center',
    letterSpacing: 2,
    fontSize: 16,
    width: '100%',
  },
  visualFlashcard: {
    width: '100%',
    padding: 10,
    borderRadius: 10,
    backgroundColor: colors.visualFlashcardBackground,
    marginVertical: 5,
    alignItems: 'center',
  },
  visualFlashcardImage: {
    width: isIpad ? '95%' : 350,
    height: isIpad ? 500 : 200,
    borderRadius: 10,
    marginBottom: 10,
  },
  visualFlashcardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
  },
  expandedFlashcardImage: {
    flex: 1,
    margin: isIpad ? 180 : 150,
    width: isIpad ? '100%' : 350,
    height: isIpad ? 400 : 400,
    resizeMode: 'contain',
  },
  expandedFlashcardTitle: {
    fontSize: isIpad ? 50 : 25,
    top: isIpad ? 180 : 120,
    fontWeight: 'bold',
    color: '#FFF',
    textShadowColor: colors.expandedFlashcardTitleTextShadow,
    textShadowOffset: { width: 1, height: 2 },
    textShadowRadius: 5,
    textAlign: 'center',
    textTransform: 'capitalize',
  },
  ExpandContainer: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: colors.primaryBackground,
  },
  header: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  headerText: {
    fontSize: 18,
    fontWeight: "bold",
  },
  settingsContainer: {
    padding: 16,
  },
  settingItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
  },
  settingText: {
    marginLeft: 16,
    fontSize: 16,
  },
  searchContainer: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 8,
  },
  searchInput: {
    height: 40,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 12,
  },
  selectionContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    marginBottom: 20,
  },
  selectionItem: {
    margin: 5,
    padding: 20,
    borderRadius: 20,
    elevation: 5,
    alignItems: 'center',
    width: isIpad ? windowWidth / 8 - 10 : windowWidth / 5 - 10,
  },
  selectionItemText: {
    fontSize: 10,
    letterSpacing: 0.5,
    fontWeight: '900',
    color: '#fff',
    marginTop: 10,
  },
  buttonContainer: {
    width: '80%',
    height: 50,
    backgroundColor: colors.buttonBackground,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  buttonText: {
    color: colors.buttonText,
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.modalOverlay,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: colors.modalContentBackground,
    padding: 20,
    borderRadius: 10,
    width: '80%',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  modalInput: {
    height: 40,
    borderColor: 'gray',
    borderWidth: 1,
    marginBottom: 15,
    padding: 10,
  },
  modalButton: {
    backgroundColor: colors.modalButtonBackground,
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  modalButtonText: {
    color: colors.modalButtonTextColor,
    fontSize: 16,
    fontWeight: 'bold',
  },
  toggleLayoutButton: {
    backgroundColor: "#FE89A9",
    padding: 12,
    alignItems: "center",
    marginTop: 16,
  },
  toggleLayoutButtonText: {
    color: "#fff",
    fontSize: 16,
  },
});

export default styles;
